services:
  # HTTPS Reverse Proxy
  proxy:
    build: .
    platform: linux/amd64
    ports:
      - "440:440"
      - "441:441"
      - "442:442"
      - "443:443"
    volumes:
      - ./routes.yaml:/etc/proxy/routes.yaml:ro
      - ./certs:/certs # Mount certs directory to access CA certificate on host
    environment:
      - RUST_LOG=debug
    depends_on:
      - app
      - api
    networks:
      - proxy-net

  api:
    image: containous/whoami
    platform: linux/amd64
    command: [ "--port", "3000" ]
    networks:
      - proxy-net

  app:
    image: containous/whoami
    platform: linux/amd64
    command: [ "--port", "3001" ]
    networks:
      - proxy-net

  ws-echo:
    image: jmalloc/echo-server
    platform: linux/amd64
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge
